### ISSUE TITLE
Install into existing venv?

### ISSUE THREAD

**Issue by hemna** [pomponchik/instld#7]
I just found your library and I find it really nice.   The only thing that I'm unsure of, is there a way to get it to install
the package into an existing virtual environment?   

I'm the maintainer of the python project called aprsd https://github.com/craigerl/aprsd and I want a mechanism that I can use from inside the app to install aprsd plugins into the existing virtual environment that users run aprsd from.

I tried using your library and it looks like it always installs the packages into a directory in /var

```
WARNING: Target directory /var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/tmpj1on95qb/lib/python3.10/site-packages/distutils-precedence.pth
```

It would be nice to specify an arg to installed to pass use_existing_env=True and have it detect if there is an existing virtual lenvironment in the shell and use that location for the install.

**Comment by pomponchik** [comment]
Hello!

Yes, there is such a possibility.

What you need to know about `instld`: by default, libraries are installed in a temporary directory, which is automatically deleted along with all the contents after the program ends (in the case of [script launch mode](https://github.com/pomponchik/instld#script-launch-mode)) or after exiting the context manager (in the case of using the context manager [`installed`](https://github.com/pomponchik/instld#context-manager-mode)). This is convenient because you don't need to have a virtual environment to run at all, however, it can create a lot of overhead if you run your program frequently.

If you need `instld` to install libraries in a specific directory, there are separate solutions for this in both launch modes:

- For script launch mode - use [special comment language](https://github.com/pomponchik/instld#special-comment-language). You need to [specify](https://github.com/pomponchik/instld#using-multiple-environments) in a special comment the path to the directory where your virtual environment is stored.

```python
import something  # instld: where path/to/the/venv
```

- For context manager mode - you need to use the `where` argument when creating the context. This feature is already present in the latest version of `instld`, but it is not described in the documentation. I will add this point to the documentation starting from version 0.0.19.

```python
with installed('some_package==1.0.0', where='path/to/the/venv')
```
